### ISSUE TITLE
CUADRO COMPARATIVO

### ISSUE THREAD

**Issue by yadiriaoliviamiguelaguilar** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-yadiriaoliviamiguelaguilar#1]
[CUADRO COMPARATIVO.docx](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-yadiriaoliviamiguelaguilar/files/9465282/CUADRO.COMPARATIVO.docx)

YADIRIA MIGUEL AGUILAR

**Comment by 11042002** [comment]
Tu calificación es de: 18.5%

**Comment by josealfredo79** [comment]
BIen hecho y revisado..
